# Generated by Django 5.2.9 on 2025-12-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='role_id',
            new_name='role',
        ),
    ]
