# Generated by Django 5.2.9 on 2025-12-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_myuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatistics',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
